<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\InvestorDocument;
use App\Models\DocumentCategory;
use App\Models\User;
use Carbon\Carbon;

class InvestorDocumentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = DocumentCategory::all();
        $users = User::where('role', 'CEO')->get();
        $adminUser = $users->first() ?? User::first();

        $documents = [
            // Financials Category
            [
                'title' => 'P&L Statement (Last 12 Months)',
                'description' => 'Monthly profit & loss breakdown for the last 12 months',
                'category_id' => $categories->where('name', 'Financials')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '01_PnL_Last12Months.xlsx',
                'file_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'file_size' => 245760,
                'priority' => 3,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(5),
                'completed_date' => Carbon::now()->subDays(5),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Complete P&L statement with monthly breakdown'
            ],
            [
                'title' => 'Balance Sheet (Current)',
                'description' => 'Current balance sheet as of end of month',
                'category_id' => $categories->where('name', 'Financials')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '02_BalanceSheet_Current.xlsx',
                'file_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'file_size' => 198432,
                'priority' => 3,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(5),
                'completed_date' => Carbon::now()->subDays(5),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Current balance sheet with asset and liability breakdown'
            ],
            [
                'title' => 'Cash Flow Statement',
                'description' => 'Monthly cash flow statement',
                'category_id' => $categories->where('name', 'Financials')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '03_CashFlow_Statement.xlsx',
                'file_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'file_size' => 187654,
                'priority' => 3,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(5),
                'completed_date' => Carbon::now()->subDays(5),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Operating, investing, and financing cash flows'
            ],
            [
                'title' => 'Revenue Analysis',
                'description' => 'Detailed revenue analysis by product and channel',
                'category_id' => $categories->where('name', 'Financials')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '04_Revenue_Analysis.xlsx',
                'file_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'file_size' => 312456,
                'priority' => 2,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(3),
                'completed_date' => Carbon::now()->subDays(3),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Revenue breakdown by product category and sales channel'
            ],
            [
                'title' => 'Expense Breakdown',
                'description' => 'Detailed expense analysis by category',
                'category_id' => $categories->where('name', 'Financials')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '05_Expense_Breakdown.xlsx',
                'file_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'file_size' => 267890,
                'priority' => 2,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(3),
                'completed_date' => Carbon::now()->subDays(3),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Operating expenses breakdown by department and category'
            ],
            [
                'title' => 'Financial Projections',
                'description' => '12-month financial projections',
                'category_id' => $categories->where('name', 'Financials')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '06_Financial_Projections.xlsx',
                'file_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'file_size' => 345678,
                'priority' => 2,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(1),
                'completed_date' => Carbon::now()->subDays(1),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Revenue, expense, and cash flow projections'
            ],
            [
                'title' => 'Valuation Model',
                'description' => 'Company valuation model and assumptions',
                'category_id' => $categories->where('name', 'Financials')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '07_Valuation_Model.xlsx',
                'file_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'file_size' => 456789,
                'priority' => 3,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(1),
                'completed_date' => Carbon::now()->subDays(1),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'DCF and comparable company valuation models'
            ],

            // Operations Category
            [
                'title' => 'Workflow Map (Zoho-Moniepoint)',
                'description' => 'Complete workflow mapping from order to delivery',
                'category_id' => $categories->where('name', 'Operations')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '08_WorkflowMap_Zoho_Moniepoint.pdf',
                'file_type' => 'application/pdf',
                'file_size' => 1234567,
                'priority' => 3,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(4),
                'completed_date' => Carbon::now()->subDays(4),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'End-to-end workflow documentation'
            ],
            [
                'title' => 'Inventory Management System',
                'description' => 'Inventory tracking and management processes',
                'category_id' => $categories->where('name', 'Operations')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '09_Inventory_Management.pdf',
                'file_type' => 'application/pdf',
                'file_size' => 987654,
                'priority' => 2,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(4),
                'completed_date' => Carbon::now()->subDays(4),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Real-time inventory tracking system documentation'
            ],
            [
                'title' => 'Package Integrity Process',
                'description' => 'Quality control and package integrity procedures',
                'category_id' => $categories->where('name', 'Operations')->first()->id,
                'status' => 'in_progress',
                'completion_status' => 'pending',
                'file_name' => '10_PackageIntegrity_Process.pdf',
                'file_type' => 'application/pdf',
                'file_size' => 756432,
                'priority' => 2,
                'is_required' => true,
                'due_date' => Carbon::now()->addDays(3),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Quality control procedures for package integrity'
            ],
            [
                'title' => 'DA Management System',
                'description' => 'Delivery agent management and performance tracking',
                'category_id' => $categories->where('name', 'Operations')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '11_DA_Management_System.pdf',
                'file_type' => 'application/pdf',
                'file_size' => 1123456,
                'priority' => 2,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(2),
                'completed_date' => Carbon::now()->subDays(2),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'DA performance tracking and management system'
            ],
            [
                'title' => 'Customer Service Processes',
                'description' => 'Customer service workflow and procedures',
                'category_id' => $categories->where('name', 'Operations')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '12_Customer_Service_Processes.pdf',
                'file_type' => 'application/pdf',
                'file_size' => 876543,
                'priority' => 2,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(2),
                'completed_date' => Carbon::now()->subDays(2),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Customer service workflow and escalation procedures'
            ],

            // Governance Category
            [
                'title' => 'Board Resolutions (2024)',
                'description' => 'All board resolutions for 2024',
                'category_id' => $categories->where('name', 'Governance')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '13_Board_Resolutions_2024.pdf',
                'file_type' => 'application/pdf',
                'file_size' => 2345678,
                'priority' => 3,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(7),
                'completed_date' => Carbon::now()->subDays(7),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Complete board resolution documentation for 2024'
            ],
            [
                'title' => 'Corporate Governance Policy',
                'description' => 'Corporate governance framework and policies',
                'category_id' => $categories->where('name', 'Governance')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '14_Corporate_Governance_Policy.pdf',
                'file_type' => 'application/pdf',
                'file_size' => 1456789,
                'priority' => 3,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(7),
                'completed_date' => Carbon::now()->subDays(7),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Comprehensive corporate governance policy'
            ],
            [
                'title' => 'Risk Management Framework',
                'description' => 'Risk identification and management procedures',
                'category_id' => $categories->where('name', 'Governance')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '15_Risk_Management_Framework.pdf',
                'file_type' => 'application/pdf',
                'file_size' => 1678901,
                'priority' => 3,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(6),
                'completed_date' => Carbon::now()->subDays(6),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Comprehensive risk management framework'
            ],
            [
                'title' => 'Compliance Audit Report',
                'description' => 'Latest compliance audit findings and recommendations',
                'category_id' => $categories->where('name', 'Governance')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '16_Compliance_Audit_Report.pdf',
                'file_type' => 'application/pdf',
                'file_size' => 1987654,
                'priority' => 3,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(6),
                'completed_date' => Carbon::now()->subDays(6),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'External compliance audit report'
            ],
            [
                'title' => 'Code of Conduct',
                'description' => 'Employee code of conduct and ethics policy',
                'category_id' => $categories->where('name', 'Governance')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '17_Code_of_Conduct.pdf',
                'file_type' => 'application/pdf',
                'file_size' => 987654,
                'priority' => 2,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(5),
                'completed_date' => Carbon::now()->subDays(5),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Employee code of conduct and ethics guidelines'
            ],
            [
                'title' => 'Data Protection Policy',
                'description' => 'Data protection and privacy policy',
                'category_id' => $categories->where('name', 'Governance')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '18_Data_Protection_Policy.pdf',
                'file_type' => 'application/pdf',
                'file_size' => 876543,
                'priority' => 2,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(5),
                'completed_date' => Carbon::now()->subDays(5),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Data protection and privacy compliance policy'
            ],

            // Vision & Strategy Category
            [
                'title' => 'Strategic Plan 2025-2027',
                'description' => 'Three-year strategic plan and objectives',
                'category_id' => $categories->where('name', 'Vision & Strategy')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '19_Strategic_Plan_2025_2027.pdf',
                'file_type' => 'application/pdf',
                'file_size' => 3456789,
                'priority' => 3,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(10),
                'completed_date' => Carbon::now()->subDays(10),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Comprehensive three-year strategic plan'
            ],
            [
                'title' => 'Market Analysis Report',
                'description' => 'Comprehensive market analysis and competitive landscape',
                'category_id' => $categories->where('name', 'Vision & Strategy')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '20_Market_Analysis_Report.pdf',
                'file_type' => 'application/pdf',
                'file_size' => 4567890,
                'priority' => 3,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(10),
                'completed_date' => Carbon::now()->subDays(10),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Detailed market analysis and competitive positioning'
            ],
            [
                'title' => 'Growth Strategy Document',
                'description' => 'Detailed growth strategy and expansion plans',
                'category_id' => $categories->where('name', 'Vision & Strategy')->first()->id,
                'status' => 'in_progress',
                'completion_status' => 'pending',
                'file_name' => '21_Growth_Strategy_Document.pdf',
                'file_type' => 'application/pdf',
                'file_size' => 2345678,
                'priority' => 3,
                'is_required' => true,
                'due_date' => Carbon::now()->addDays(5),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Growth strategy and expansion roadmap'
            ],
            [
                'title' => 'Product Roadmap',
                'description' => 'Product development roadmap and timeline',
                'category_id' => $categories->where('name', 'Vision & Strategy')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '22_Product_Roadmap.pdf',
                'file_type' => 'application/pdf',
                'file_size' => 1876543,
                'priority' => 2,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(8),
                'completed_date' => Carbon::now()->subDays(8),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Product development roadmap and timeline'
            ],
            [
                'title' => 'Technology Strategy',
                'description' => 'Technology infrastructure and development strategy',
                'category_id' => $categories->where('name', 'Vision & Strategy')->first()->id,
                'status' => 'in_progress',
                'completion_status' => 'pending',
                'file_name' => '23_Technology_Strategy.pdf',
                'file_type' => 'application/pdf',
                'file_size' => 2987654,
                'priority' => 2,
                'is_required' => true,
                'due_date' => Carbon::now()->addDays(7),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Technology infrastructure and development strategy'
            ],
            [
                'title' => 'Brand Strategy Document',
                'description' => 'Brand positioning and marketing strategy',
                'category_id' => $categories->where('name', 'Vision & Strategy')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '24_Brand_Strategy_Document.pdf',
                'file_type' => 'application/pdf',
                'file_size' => 1654321,
                'priority' => 2,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(8),
                'completed_date' => Carbon::now()->subDays(8),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Brand positioning and marketing strategy'
            ],

            // Owner Oversight Category
            [
                'title' => 'Owner Control Framework',
                'description' => 'Owner oversight and control mechanisms',
                'category_id' => $categories->where('name', 'Risk Management')->first()->id,
                'status' => 'not_ready',
                'completion_status' => 'incomplete',
                'file_name' => '25_Owner_Control_Framework.pdf',
                'file_type' => 'application/pdf',
                'file_size' => 0,
                'priority' => 3,
                'is_required' => true,
                'due_date' => Carbon::now()->addDays(10),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Owner oversight and control framework'
            ],
            [
                'title' => 'Financial Control Procedures',
                'description' => 'Financial control and approval procedures',
                'category_id' => $categories->where('name', 'Risk Management')->first()->id,
                'status' => 'in_progress',
                'completion_status' => 'pending',
                'file_name' => '26_Financial_Control_Procedures.pdf',
                'file_type' => 'application/pdf',
                'file_size' => 1234567,
                'priority' => 3,
                'is_required' => true,
                'due_date' => Carbon::now()->addDays(5),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Financial control and approval procedures'
            ],
            [
                'title' => 'Performance Monitoring System',
                'description' => 'KPI monitoring and performance tracking system',
                'category_id' => $categories->where('name', 'Risk Management')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '27_Performance_Monitoring_System.pdf',
                'file_type' => 'application/pdf',
                'file_size' => 1876543,
                'priority' => 2,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(3),
                'completed_date' => Carbon::now()->subDays(3),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'KPI monitoring and performance tracking system'
            ],
            [
                'title' => 'Audit Trail Documentation',
                'description' => 'Comprehensive audit trail and logging procedures',
                'category_id' => $categories->where('name', 'Risk Management')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '28_Audit_Trail_Documentation.pdf',
                'file_type' => 'application/pdf',
                'file_size' => 1456789,
                'priority' => 2,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(3),
                'completed_date' => Carbon::now()->subDays(3),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Comprehensive audit trail and logging procedures'
            ],
            [
                'title' => 'Escalation Procedures',
                'description' => 'Issue escalation and resolution procedures',
                'category_id' => $categories->where('name', 'Risk Management')->first()->id,
                'status' => 'ready',
                'completion_status' => 'complete',
                'file_name' => '29_Escalation_Procedures.pdf',
                'file_type' => 'application/pdf',
                'file_size' => 987654,
                'priority' => 2,
                'is_required' => true,
                'due_date' => Carbon::now()->subDays(2),
                'completed_date' => Carbon::now()->subDays(2),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Issue escalation and resolution procedures'
            ],
            [
                'title' => 'Compliance Monitoring',
                'description' => 'Ongoing compliance monitoring and reporting',
                'category_id' => $categories->where('name', 'Risk Management')->first()->id,
                'status' => 'not_ready',
                'completion_status' => 'incomplete',
                'file_name' => '30_Compliance_Monitoring.pdf',
                'file_type' => 'application/pdf',
                'file_size' => 0,
                'priority' => 2,
                'is_required' => true,
                'due_date' => Carbon::now()->addDays(12),
                'assigned_to' => $adminUser->id,
                'created_by' => $adminUser->id,
                'notes' => 'Ongoing compliance monitoring and reporting procedures'
            ]
        ];

        foreach ($documents as $documentData) {
            InvestorDocument::updateOrCreate(
                ['title' => $documentData['title']],
                $documentData
            );
        }

        $this->command->info('Investor documents seeded successfully!');
    }
}
