#!/usr/bin/env bash

BASE="/Users/yesideasekun/vitalvida-api"

echo "🚀 START COMMANDS:"
echo "cd $BASE/logistics && npm install && npm run dev"
echo "cd $BASE/inventory-management && npm install && npm run dev"
echo "cd $BASE/telesales && npm install && npm run dev"
echo "cd $BASE/delivery-agent && npm install && npm run dev"
echo "cd $BASE/accountant && npm install && npm run dev"
echo "cd $BASE/financial-controller && npm install && npm run dev"
echo "cd $BASE/gm && npm install && npm run dev"
echo "cd $BASE/ceo && npm install && npm run dev"
echo "cd $BASE/hr && npm install && npm run dev"
echo "cd $BASE/investor && npm install && npm run dev"
echo "cd $BASE/manufacturing && npm install && npm run dev"
echo "cd $BASE/media-buyer && npm install && npm run dev"

echo ""
echo "🔧 SYSTEM AUTOMATION:"
echo "cd $BASE/vitalvida-crm && npm install && npm run dev"
echo "cd $BASE/vitalvida-inventory && npm install && npm run dev"
echo "cd $BASE/vitalvida-books && npm install && npm run dev"
echo "cd $BASE/vitalvida-marketing && npm install && npm run dev"

echo ""
echo "🎯 QUICK ACCESS URLs (after starting):"
echo "logistics: http://localhost:3004"
echo "inventory-management: http://localhost:3005"
echo "telesales: http://localhost:3006"
echo "delivery-agent: http://localhost:3007"
echo "accountant: http://localhost:3008"
echo "financial-controller: http://localhost:3009"
echo "gm: http://localhost:3010"
echo "ceo: http://localhost:3011"
echo "hr: http://localhost:3012"
echo "investor: http://localhost:3013"
echo "manufacturing: http://localhost:3014"
echo "media-buyer: http://localhost:3015"
echo "vitalvida-crm: http://localhost:3016"
echo "vitalvida-inventory: http://localhost:3017"
echo "vitalvida-books: http://localhost:3018"
echo "vitalvida-marketing: http://localhost:3019"
